repos:
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
  - repo: local
    hooks:
      - id: coverage
        name: Coverage
        entry: >-
          bash -c 'SIM=icarus coverage run
          --source=basil -m pytest
          -q --disable-warnings
          tests/test_*.py examples/*/*/test_*.py
          && coverage xml -q -o coverage.xml
          && diff-cover coverage.xml
          --compare-branch=origin/master
          --show-uncovered'
        language: system
        pass_filenames: false
        verbose: true
        files: ^(basil/|tests/|examples/).*\.py$
        stages: [pre-commit]
