set_property SRC_FILE_INFO {cfile:/users/rleiser/work/basil_branch/examples/tdc_bdaq/SiTCP.xdc rfile:../../../SiTCP.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/users/rleiser/work/basil_branch/examples/tdc_bdaq/bdaq53.xdc rfile:../../../bdaq53.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/users/rleiser/work/basil_branch/examples/tdc_bdaq/tdc_bdaq.xdc rfile:../../../tdc_bdaq.xdc id:3} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */GMII_RXBUF/cmpWrAddr*/C}] -to [get_pins -hier -filter {name =~ */GMII_RXBUF/smpWrStatusAddr*/D}] 5.500
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */GMII_TXBUF/orRdAct*/C}] -to [get_pins -hier -filter {name =~ */GMII_TXBUF/irRdAct*/D}] 5.500
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */GMII_TXBUF/muxEndTgl/C}] -to [get_pins -hier -filter {name =~ */GMII_TXBUF/rsmpMuxTrnsEnd*/D}] 5.500
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX10Data*/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/irMacFlowEnb/D}] 5.500
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX12Data*/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyMac*/D}] 5.500
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX13Data*/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyMac*/D}] 5.500
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX14Data*/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyMac*/D}] 5.500
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX15Data*/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyMac*/D}] 5.500
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX16Data*/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyMac*/D}] 5.500
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX17Data*/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyMac*/D}] 5.500
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX18Data*/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyIp*/D}] 5.500
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX19Data*/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyIp*/D}] 5.500
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX1AData*/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyIp*/D}] 5.500
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */SiTCP_INT_REG/regX1BData*/C}] -to [get_pins -hier -filter {name =~ */GMII_RXCNT/muxMyIp*/D}] 5.500
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */GMII_TXBUF/dlyBank0LastWrAddr*/C}] -to [get_pins -hier -filter {name =~ */GMII_TXBUF/rsmpBank0LastWrAddr*/D}] 5.500
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */GMII_TXBUF/dlyBank1LastWrAddr*/C}] -to [get_pins -hier -filter {name =~ */GMII_TXBUF/rsmpBank1LastWrAddr*/D}] 5.500
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */GMII_TXBUF/memRdReq*/C}] -to [get_pins -hier -filter {name =~ */GMII_TXBUF/irMemRdReq*/D}] 5.500
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */GMII_RXCNT/orMacTim*/C}] -to [get_pins -hier -filter {name =~ */GMII_TXCNT/irMacPauseTime*/D}] 5.500
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only -from [get_pins -hier -filter {name =~ */GMII_RXCNT/orMacPause/C}] -to [get_pins -hier -filter {name =~ */GMII_TXCNT/irMacPauseExe_0/D}] 5.500
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_pins -hier -filter {name =~ */SiTCP_INT/SiTCP_RESET_OUT/C}]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AA4 [get_ports clkin]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G9 [get_ports RESET_N]
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B25 [get_ports mdio_phy_mdc]
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B26 [get_ports mdio_phy_mdio]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports phy_rst_n]
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G22 [get_ports rgmii_rxc]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F23 [get_ports rgmii_rx_ctl]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H23 [get_ports {rgmii_rxd[0]}]
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H24 [get_ports {rgmii_rxd[1]}]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J21 [get_ports {rgmii_rxd[2]}]
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H22 [get_ports {rgmii_rxd[3]}]
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K23 [get_ports rgmii_txc]
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J23 [get_ports rgmii_tx_ctl]
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J24 [get_ports {rgmii_txd[0]}]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J25 [get_ports {rgmii_txd[1]}]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L22 [get_ports {rgmii_txd[2]}]
set_property src_info {type:XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K22 [get_ports {rgmii_txd[3]}]
set_property src_info {type:XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U9 [get_ports {LED[0]}]
set_property src_info {type:XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {LED[1]}]
set_property src_info {type:XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13 [get_ports {LED[2]}]
set_property src_info {type:XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W13 [get_ports {LED[3]}]
set_property src_info {type:XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E21 [get_ports {LED[4]}]
set_property src_info {type:XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E22 [get_ports {LED[5]}]
set_property src_info {type:XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D21 [get_ports {LED[6]}]
set_property src_info {type:XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C22 [get_ports {LED[7]}]
set_property src_info {type:XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C19 [get_ports sig_in]
set_property src_info {type:XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports trig_in]
set_property src_info {type:XDC file:3 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC SLICE_X38Y3 [get_cells -hier -regexp .*FirstCell/CARRY4_inst]
set_property src_info {type:XDC file:3 line:42 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:3 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 2 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:3 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:3 line:52 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list CLK160PLL_BUFG]]
set_property src_info {type:XDC file:3 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 7 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {i_tdc/i_tdc_core/encoder/position_out[0]} {i_tdc/i_tdc_core/encoder/position_out[1]} {i_tdc/i_tdc_core/encoder/position_out[2]} {i_tdc/i_tdc_core/encoder/position_out[3]} {i_tdc/i_tdc_core/encoder/position_out[4]} {i_tdc/i_tdc_core/encoder/position_out[5]} {i_tdc/i_tdc_core/encoder/position_out[6]}]]
set_property src_info {type:XDC file:3 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 96 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:3 line:59 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {i_tdc/i_tdc_core/selected_sample[0]} {i_tdc/i_tdc_core/selected_sample[1]} {i_tdc/i_tdc_core/selected_sample[2]} {i_tdc/i_tdc_core/selected_sample[3]} {i_tdc/i_tdc_core/selected_sample[4]} {i_tdc/i_tdc_core/selected_sample[5]} {i_tdc/i_tdc_core/selected_sample[6]} {i_tdc/i_tdc_core/selected_sample[7]} {i_tdc/i_tdc_core/selected_sample[8]} {i_tdc/i_tdc_core/selected_sample[9]} {i_tdc/i_tdc_core/selected_sample[10]} {i_tdc/i_tdc_core/selected_sample[11]} {i_tdc/i_tdc_core/selected_sample[12]} {i_tdc/i_tdc_core/selected_sample[13]} {i_tdc/i_tdc_core/selected_sample[14]} {i_tdc/i_tdc_core/selected_sample[15]} {i_tdc/i_tdc_core/selected_sample[16]} {i_tdc/i_tdc_core/selected_sample[17]} {i_tdc/i_tdc_core/selected_sample[18]} {i_tdc/i_tdc_core/selected_sample[19]} {i_tdc/i_tdc_core/selected_sample[20]} {i_tdc/i_tdc_core/selected_sample[21]} {i_tdc/i_tdc_core/selected_sample[22]} {i_tdc/i_tdc_core/selected_sample[23]} {i_tdc/i_tdc_core/selected_sample[24]} {i_tdc/i_tdc_core/selected_sample[25]} {i_tdc/i_tdc_core/selected_sample[26]} {i_tdc/i_tdc_core/selected_sample[27]} {i_tdc/i_tdc_core/selected_sample[28]} {i_tdc/i_tdc_core/selected_sample[29]} {i_tdc/i_tdc_core/selected_sample[30]} {i_tdc/i_tdc_core/selected_sample[31]} {i_tdc/i_tdc_core/selected_sample[32]} {i_tdc/i_tdc_core/selected_sample[33]} {i_tdc/i_tdc_core/selected_sample[34]} {i_tdc/i_tdc_core/selected_sample[35]} {i_tdc/i_tdc_core/selected_sample[36]} {i_tdc/i_tdc_core/selected_sample[37]} {i_tdc/i_tdc_core/selected_sample[38]} {i_tdc/i_tdc_core/selected_sample[39]} {i_tdc/i_tdc_core/selected_sample[40]} {i_tdc/i_tdc_core/selected_sample[41]} {i_tdc/i_tdc_core/selected_sample[42]} {i_tdc/i_tdc_core/selected_sample[43]} {i_tdc/i_tdc_core/selected_sample[44]} {i_tdc/i_tdc_core/selected_sample[45]} {i_tdc/i_tdc_core/selected_sample[46]} {i_tdc/i_tdc_core/selected_sample[47]} {i_tdc/i_tdc_core/selected_sample[48]} {i_tdc/i_tdc_core/selected_sample[49]} {i_tdc/i_tdc_core/selected_sample[50]} {i_tdc/i_tdc_core/selected_sample[51]} {i_tdc/i_tdc_core/selected_sample[52]} {i_tdc/i_tdc_core/selected_sample[53]} {i_tdc/i_tdc_core/selected_sample[54]} {i_tdc/i_tdc_core/selected_sample[55]} {i_tdc/i_tdc_core/selected_sample[56]} {i_tdc/i_tdc_core/selected_sample[57]} {i_tdc/i_tdc_core/selected_sample[58]} {i_tdc/i_tdc_core/selected_sample[59]} {i_tdc/i_tdc_core/selected_sample[60]} {i_tdc/i_tdc_core/selected_sample[61]} {i_tdc/i_tdc_core/selected_sample[62]} {i_tdc/i_tdc_core/selected_sample[63]} {i_tdc/i_tdc_core/selected_sample[64]} {i_tdc/i_tdc_core/selected_sample[65]} {i_tdc/i_tdc_core/selected_sample[66]} {i_tdc/i_tdc_core/selected_sample[67]} {i_tdc/i_tdc_core/selected_sample[68]} {i_tdc/i_tdc_core/selected_sample[69]} {i_tdc/i_tdc_core/selected_sample[70]} {i_tdc/i_tdc_core/selected_sample[71]} {i_tdc/i_tdc_core/selected_sample[72]} {i_tdc/i_tdc_core/selected_sample[73]} {i_tdc/i_tdc_core/selected_sample[74]} {i_tdc/i_tdc_core/selected_sample[75]} {i_tdc/i_tdc_core/selected_sample[76]} {i_tdc/i_tdc_core/selected_sample[77]} {i_tdc/i_tdc_core/selected_sample[78]} {i_tdc/i_tdc_core/selected_sample[79]} {i_tdc/i_tdc_core/selected_sample[80]} {i_tdc/i_tdc_core/selected_sample[81]} {i_tdc/i_tdc_core/selected_sample[82]} {i_tdc/i_tdc_core/selected_sample[83]} {i_tdc/i_tdc_core/selected_sample[84]} {i_tdc/i_tdc_core/selected_sample[85]} {i_tdc/i_tdc_core/selected_sample[86]} {i_tdc/i_tdc_core/selected_sample[87]} {i_tdc/i_tdc_core/selected_sample[88]} {i_tdc/i_tdc_core/selected_sample[89]} {i_tdc/i_tdc_core/selected_sample[90]} {i_tdc/i_tdc_core/selected_sample[91]} {i_tdc/i_tdc_core/selected_sample[92]} {i_tdc/i_tdc_core/selected_sample[93]} {i_tdc/i_tdc_core/selected_sample[94]} {i_tdc/i_tdc_core/selected_sample[95]}]]
set_property src_info {type:XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:3 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:3 line:63 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {i_tdc/i_tdc_core/tdc_state_delayed[0]} {i_tdc/i_tdc_core/tdc_state_delayed[1]} {i_tdc/i_tdc_core/tdc_state_delayed[2]} {i_tdc/i_tdc_core/tdc_state_delayed[3]}]]
set_property src_info {type:XDC file:3 line:64 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:3 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:3 line:67 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {i_tdc/i_tdc_core/tdc_state[0]} {i_tdc/i_tdc_core/tdc_state[1]} {i_tdc/i_tdc_core/tdc_state[2]} {i_tdc/i_tdc_core/tdc_state[3]}]]
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:3 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:3 line:71 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {i_tdc/i_tdc_core/fine_time_delayed[0]} {i_tdc/i_tdc_core/fine_time_delayed[1]}]]
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {i_tdc/i_tdc_core/input_mux_addr[0]} {i_tdc/i_tdc_core/input_mux_addr[1]}]]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {i_tdc/i_tdc_core/hit_status[0]} {i_tdc/i_tdc_core/hit_status[1]}]]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:3 line:83 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {i_tdc/i_tdc_core/fine_time[0]} {i_tdc/i_tdc_core/fine_time[1]}]]
set_property src_info {type:XDC file:3 line:84 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {i_tdc/i_tdc_core/corse_time_delayed[0]} {i_tdc/i_tdc_core/corse_time_delayed[1]} {i_tdc/i_tdc_core/corse_time_delayed[2]} {i_tdc/i_tdc_core/corse_time_delayed[3]} {i_tdc/i_tdc_core/corse_time_delayed[4]} {i_tdc/i_tdc_core/corse_time_delayed[5]} {i_tdc/i_tdc_core/corse_time_delayed[6]} {i_tdc/i_tdc_core/corse_time_delayed[7]} {i_tdc/i_tdc_core/corse_time_delayed[8]} {i_tdc/i_tdc_core/corse_time_delayed[9]} {i_tdc/i_tdc_core/corse_time_delayed[10]} {i_tdc/i_tdc_core/corse_time_delayed[11]} {i_tdc/i_tdc_core/corse_time_delayed[12]} {i_tdc/i_tdc_core/corse_time_delayed[13]} {i_tdc/i_tdc_core/corse_time_delayed[14]} {i_tdc/i_tdc_core/corse_time_delayed[15]}]]
set_property src_info {type:XDC file:3 line:88 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:3 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:3 line:91 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list i_tdc/sig_in_IBUF]]
set_property src_info {type:XDC file:3 line:92 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:3 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:3 line:95 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list i_tdc/i_tdc_core/tdl_input]]
set_property src_info {type:XDC file:3 line:96 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:3 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:3 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:3 line:99 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list i_tdc/i_tdc_core/trig_in_IBUF]]
set_property src_info {type:XDC file:3 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:3 line:103 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets CLK160PLL_BUFG]
