
####################################################################################
# Generated by PlanAhead 14.7 built on 'Fri Sep 27 19:29:51 MDT 2013' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'Mercury KX1.ucf'
####################################################################################

set_property DIFF_TERM FALSE [get_ports sys_clk_n]

set_property DIFF_TERM FALSE [get_ports sys_clk_p]

set_property PACKAGE_PIN AA3 [get_ports Clk100]
set_property IOSTANDARD LVCMOS15 [get_ports Clk100]

set_property PACKAGE_PIN G22 [get_ports fx3_pclk_100MHz]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:1
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_pclk_100MHz' has been applied to the port object 'fx3_pclk_100MHz'.
set_property IOSTANDARD LVCMOS33 [get_ports fx3_pclk_100MHz]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:1
# The conversion of 'SLEW' constraint on 'net' object 'fx3_pclk_100MHz' has been applied to the port object 'fx3_pclk_100MHz'.
set_property SLEW FAST [get_ports fx3_pclk_100MHz]


set_property PACKAGE_PIN A23 [get_ports {fx3_bus[0]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:3
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[0]' has been applied to the port object 'fx3_bus[0]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[0]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:3
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[0]' has been applied to the port object 'fx3_bus[0]'.
set_property SLEW FAST [get_ports {fx3_bus[0]}]
set_property PACKAGE_PIN A24 [get_ports {fx3_bus[1]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:4
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[1]' has been applied to the port object 'fx3_bus[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[1]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:4
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[1]' has been applied to the port object 'fx3_bus[1]'.
set_property SLEW FAST [get_ports {fx3_bus[1]}]
set_property PACKAGE_PIN C21 [get_ports {fx3_bus[10]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:5
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[10]' has been applied to the port object 'fx3_bus[10]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[10]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:5
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[10]' has been applied to the port object 'fx3_bus[10]'.
set_property SLEW FAST [get_ports {fx3_bus[10]}]
set_property PACKAGE_PIN B21 [get_ports {fx3_bus[11]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:6
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[11]' has been applied to the port object 'fx3_bus[11]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[11]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:6
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[11]' has been applied to the port object 'fx3_bus[11]'.
set_property SLEW FAST [get_ports {fx3_bus[11]}]
set_property PACKAGE_PIN D23 [get_ports {fx3_bus[12]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:7
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[12]' has been applied to the port object 'fx3_bus[12]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[12]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:7
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[12]' has been applied to the port object 'fx3_bus[12]'.
set_property SLEW FAST [get_ports {fx3_bus[12]}]
set_property PACKAGE_PIN D24 [get_ports {fx3_bus[13]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:8
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[13]' has been applied to the port object 'fx3_bus[13]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[13]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:8
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[13]' has been applied to the port object 'fx3_bus[13]'.
set_property SLEW FAST [get_ports {fx3_bus[13]}]
set_property PACKAGE_PIN F22 [get_ports {fx3_bus[14]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:9
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[14]' has been applied to the port object 'fx3_bus[14]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[14]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:9
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[14]' has been applied to the port object 'fx3_bus[14]'.
set_property SLEW FAST [get_ports {fx3_bus[14]}]
set_property PACKAGE_PIN E23 [get_ports {fx3_bus[15]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:10
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[15]' has been applied to the port object 'fx3_bus[15]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[15]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:10
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[15]' has been applied to the port object 'fx3_bus[15]'.
set_property SLEW FAST [get_ports {fx3_bus[15]}]
set_property PACKAGE_PIN G24 [get_ports {fx3_bus[16]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:11
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[16]' has been applied to the port object 'fx3_bus[16]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[16]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:11
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[16]' has been applied to the port object 'fx3_bus[16]'.
set_property SLEW FAST [get_ports {fx3_bus[16]}]
set_property PACKAGE_PIN F24 [get_ports {fx3_bus[17]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:12
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[17]' has been applied to the port object 'fx3_bus[17]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[17]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:12
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[17]' has been applied to the port object 'fx3_bus[17]'.
set_property SLEW FAST [get_ports {fx3_bus[17]}]
set_property PACKAGE_PIN E25 [get_ports {fx3_bus[18]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:13
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[18]' has been applied to the port object 'fx3_bus[18]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[18]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:13
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[18]' has been applied to the port object 'fx3_bus[18]'.
set_property SLEW FAST [get_ports {fx3_bus[18]}]
set_property PACKAGE_PIN D25 [get_ports {fx3_bus[19]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:14
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[19]' has been applied to the port object 'fx3_bus[19]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[19]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:14
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[19]' has been applied to the port object 'fx3_bus[19]'.
set_property SLEW FAST [get_ports {fx3_bus[19]}]
set_property PACKAGE_PIN D26 [get_ports {fx3_bus[2]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:15
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[2]' has been applied to the port object 'fx3_bus[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[2]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:15
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[2]' has been applied to the port object 'fx3_bus[2]'.
set_property SLEW FAST [get_ports {fx3_bus[2]}]
set_property PACKAGE_PIN G25 [get_ports {fx3_bus[20]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:16
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[20]' has been applied to the port object 'fx3_bus[20]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[20]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:16
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[20]' has been applied to the port object 'fx3_bus[20]'.
set_property SLEW FAST [get_ports {fx3_bus[20]}]
set_property PACKAGE_PIN G26 [get_ports {fx3_bus[21]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:17
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[21]' has been applied to the port object 'fx3_bus[21]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[21]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:17
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[21]' has been applied to the port object 'fx3_bus[21]'.
set_property SLEW FAST [get_ports {fx3_bus[21]}]
set_property PACKAGE_PIN F25 [get_ports {fx3_bus[22]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:18
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[22]' has been applied to the port object 'fx3_bus[22]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[22]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:18
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[22]' has been applied to the port object 'fx3_bus[22]'.
set_property SLEW FAST [get_ports {fx3_bus[22]}]
set_property PACKAGE_PIN E26 [get_ports {fx3_bus[23]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:19
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[23]' has been applied to the port object 'fx3_bus[23]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[23]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:19
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[23]' has been applied to the port object 'fx3_bus[23]'.
set_property SLEW FAST [get_ports {fx3_bus[23]}]
set_property PACKAGE_PIN J26 [get_ports {fx3_bus[24]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:20
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[24]' has been applied to the port object 'fx3_bus[24]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[24]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:20
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[24]' has been applied to the port object 'fx3_bus[24]'.
set_property SLEW FAST [get_ports {fx3_bus[24]}]
set_property PACKAGE_PIN H26 [get_ports {fx3_bus[25]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:21
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[25]' has been applied to the port object 'fx3_bus[25]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[25]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:21
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[25]' has been applied to the port object 'fx3_bus[25]'.
set_property SLEW FAST [get_ports {fx3_bus[25]}]
set_property PACKAGE_PIN H21 [get_ports {fx3_bus[26]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:22
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[26]' has been applied to the port object 'fx3_bus[26]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[26]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:22
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[26]' has been applied to the port object 'fx3_bus[26]'.
set_property SLEW FAST [get_ports {fx3_bus[26]}]
set_property PACKAGE_PIN G21 [get_ports {fx3_bus[27]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:23
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[27]' has been applied to the port object 'fx3_bus[27]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[27]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:23
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[27]' has been applied to the port object 'fx3_bus[27]'.
set_property SLEW FAST [get_ports {fx3_bus[27]}]
set_property PACKAGE_PIN H23 [get_ports {fx3_bus[28]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:24
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[28]' has been applied to the port object 'fx3_bus[28]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[28]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:24
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[28]' has been applied to the port object 'fx3_bus[28]'.
set_property SLEW FAST [get_ports {fx3_bus[28]}]
set_property PACKAGE_PIN H24 [get_ports {fx3_bus[29]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:25
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[29]' has been applied to the port object 'fx3_bus[29]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[29]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:25
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[29]' has been applied to the port object 'fx3_bus[29]'.
set_property SLEW FAST [get_ports {fx3_bus[29]}]
set_property PACKAGE_PIN C26 [get_ports {fx3_bus[3]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:26
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[3]' has been applied to the port object 'fx3_bus[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[3]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:26
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[3]' has been applied to the port object 'fx3_bus[3]'.
set_property SLEW FAST [get_ports {fx3_bus[3]}]
set_property PACKAGE_PIN J21 [get_ports {fx3_bus[30]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:27
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[30]' has been applied to the port object 'fx3_bus[30]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[30]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:27
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[30]' has been applied to the port object 'fx3_bus[30]'.
set_property SLEW FAST [get_ports {fx3_bus[30]}]
set_property PACKAGE_PIN H22 [get_ports {fx3_bus[31]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:28
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[31]' has been applied to the port object 'fx3_bus[31]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[31]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:28
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[31]' has been applied to the port object 'fx3_bus[31]'.
set_property SLEW FAST [get_ports {fx3_bus[31]}]
set_property PACKAGE_PIN D21 [get_ports {fx3_bus[4]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:29
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[4]' has been applied to the port object 'fx3_bus[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[4]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:29
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[4]' has been applied to the port object 'fx3_bus[4]'.
set_property SLEW FAST [get_ports {fx3_bus[4]}]
set_property PACKAGE_PIN C22 [get_ports {fx3_bus[5]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:30
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[5]' has been applied to the port object 'fx3_bus[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[5]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:30
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[5]' has been applied to the port object 'fx3_bus[5]'.
set_property SLEW FAST [get_ports {fx3_bus[5]}]
set_property PACKAGE_PIN B20 [get_ports {fx3_bus[6]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:31
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[6]' has been applied to the port object 'fx3_bus[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[6]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:31
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[6]' has been applied to the port object 'fx3_bus[6]'.
set_property SLEW FAST [get_ports {fx3_bus[6]}]
set_property PACKAGE_PIN A20 [get_ports {fx3_bus[7]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:32
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[7]' has been applied to the port object 'fx3_bus[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[7]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:32
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[7]' has been applied to the port object 'fx3_bus[7]'.
set_property SLEW FAST [get_ports {fx3_bus[7]}]
set_property PACKAGE_PIN E21 [get_ports {fx3_bus[8]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:33
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[8]' has been applied to the port object 'fx3_bus[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[8]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:33
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[8]' has been applied to the port object 'fx3_bus[8]'.
set_property SLEW FAST [get_ports {fx3_bus[8]}]
set_property PACKAGE_PIN E22 [get_ports {fx3_bus[9]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:34
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_bus[9]' has been applied to the port object 'fx3_bus[9]'.
set_property IOSTANDARD LVCMOS33 [get_ports {fx3_bus[9]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:34
# The conversion of 'SLEW' constraint on 'net' object 'fx3_bus[9]' has been applied to the port object 'fx3_bus[9]'.
set_property SLEW FAST [get_ports {fx3_bus[9]}]

# GPIO17
set_property PACKAGE_PIN L23 [get_ports fx3_cs]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:36
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_cs' has been applied to the port object 'fx3_cs'.
set_property IOSTANDARD LVCMOS33 [get_ports fx3_cs]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:36
# The conversion of 'SLEW' constraint on 'net' object 'fx3_cs' has been applied to the port object 'fx3_cs'.
set_property SLEW FAST [get_ports fx3_cs]
# GPIO20
# set_property PACKAGE_PIN K22 [get_ports fx3_rd]
#set_property PACKAGE_PIN K22 [get_ports fx3_counten]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:37
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_rd' has been applied to the port object 'fx3_rd'.
# set_property IOSTANDARD LVCMOS33 [get_ports fx3_rd]
#set_property IOSTANDARD LVCMOS33 [get_ports fx3_counten]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:37
# The conversion of 'SLEW' constraint on 'net' object 'fx3_rd' has been applied to the port object 'fx3_rd'.
# set_property SLEW FAST [get_ports fx3_rd]
#set_property SLEW FAST [get_ports fx3_counten]
# GPIO18
set_property PACKAGE_PIN L22 [get_ports fx3_wr]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:38
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_wr' has been applied to the port object 'fx3_wr'.
set_property IOSTANDARD LVCMOS33 [get_ports fx3_wr]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:38
# The conversion of 'SLEW' constraint on 'net' object 'fx3_wr' has been applied to the port object 'fx3_wr'.
set_property SLEW FAST [get_ports fx3_wr]
# GPIO19
set_property PACKAGE_PIN C24 [get_ports fx3_oe]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:39
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_oe' has been applied to the port object 'fx3_oe'.
set_property IOSTANDARD LVCMOS33 [get_ports fx3_oe]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:39
# The conversion of 'SLEW' constraint on 'net' object 'fx3_oe' has been applied to the port object 'fx3_oe'.
set_property SLEW FAST [get_ports fx3_oe]
# GPIO29 (AD0)
#set_property PACKAGE_PIN J24 [get_ports fx3_aden]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:40
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_aden' has been applied to the port object 'fx3_aden'.
#set_property IOSTANDARD LVCMOS33 [get_ports fx3_aden]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:40
# The conversion of 'SLEW' constraint on 'net' object 'fx3_aden' has been applied to the port object 'fx3_aden'.
#set_property SLEW FAST [get_ports fx3_aden]
# GPIO28 (AD1)
#set_property PACKAGE_PIN J25 [get_ports fx3_rst]
# Button!
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:41
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_rst' has been applied to the port object 'fx3_rst'.
set_property IOSTANDARD LVCMOS33 [get_ports fx3_rst]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:41
# The conversion of 'SLEW' constraint on 'net' object 'fx3_rst' has been applied to the port object 'fx3_rst'.
set_property SLEW FAST [get_ports fx3_rst]

# GPIO21  (FLAG_A)
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:43
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_rdy' has been applied to the port object 'fx3_rdy'.
set_property IOSTANDARD LVCMOS33 [get_ports fx3_rdy]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:43
# The conversion of 'SLEW' constraint on 'net' object 'fx3_rdy' has been applied to the port object 'fx3_rdy'.
set_property SLEW FAST [get_ports fx3_rdy]
# GPIO22  (FLAG_B)
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:44
# The conversion of 'IOSTANDARD' constraint on 'net' object 'fx3_ack' has been applied to the port object 'fx3_ack'.
set_property IOSTANDARD LVCMOS33 [get_ports fx3_ack]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:44
# The conversion of 'SLEW' constraint on 'net' object 'fx3_ack' has been applied to the port object 'fx3_ack'.
set_property SLEW FAST [get_ports fx3_ack]

set_property PACKAGE_PIN M17 [get_ports {led[1]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:46
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[1]' has been applied to the port object 'led[1]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:46
# The conversion of 'SLEW' constraint on 'net' object 'led[1]' has been applied to the port object 'led[1]'.
set_property SLEW SLOW [get_ports {led[1]}]
set_property PACKAGE_PIN L18 [get_ports {led[2]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:47
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[2]' has been applied to the port object 'led[2]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:47
# The conversion of 'SLEW' constraint on 'net' object 'led[2]' has been applied to the port object 'led[2]'.
set_property SLEW SLOW [get_ports {led[2]}]
set_property PACKAGE_PIN L17 [get_ports {led[3]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:48
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[3]' has been applied to the port object 'led[3]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:48
# The conversion of 'SLEW' constraint on 'net' object 'led[3]' has been applied to the port object 'led[3]'.
set_property SLEW SLOW [get_ports {led[3]}]
set_property PACKAGE_PIN K18 [get_ports {led[4]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:49
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[4]' has been applied to the port object 'led[4]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:49
# The conversion of 'SLEW' constraint on 'net' object 'led[4]' has been applied to the port object 'led[4]'.
set_property SLEW SLOW [get_ports {led[4]}]
set_property PACKAGE_PIN P26 [get_ports {led[5]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:50
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[5]' has been applied to the port object 'led[5]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:50
# The conversion of 'SLEW' constraint on 'net' object 'led[5]' has been applied to the port object 'led[5]'.
set_property SLEW SLOW [get_ports {led[5]}]
set_property PACKAGE_PIN M25 [get_ports {led[6]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:51
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[6]' has been applied to the port object 'led[6]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:51
# The conversion of 'SLEW' constraint on 'net' object 'led[6]' has been applied to the port object 'led[6]'.
set_property SLEW SLOW [get_ports {led[6]}]
set_property PACKAGE_PIN L25 [get_ports {led[7]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:52
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[7]' has been applied to the port object 'led[7]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:52
# The conversion of 'SLEW' constraint on 'net' object 'led[7]' has been applied to the port object 'led[7]'.
set_property SLEW SLOW [get_ports {led[7]}]
set_property PACKAGE_PIN P23 [get_ports {led[8]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:53
# The conversion of 'IOSTANDARD' constraint on 'net' object 'led[8]' has been applied to the port object 'led[8]'.
set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:53
# The conversion of 'SLEW' constraint on 'net' object 'led[8]' has been applied to the port object 'led[8]'.
set_property SLEW SLOW [get_ports {led[8]}]

set_property PACKAGE_PIN P20 [get_ports reset_fx3]
set_property IOSTANDARD LVCMOS33 [get_ports reset_fx3]
set_property SLEW SLOW [get_ports reset_fx3]

set_property PACKAGE_PIN K22 [get_ports fx3_rd_finish]
set_property IOSTANDARD LVCMOS33 [get_ports fx3_rd_finish]
set_property SLEW FAST [get_ports fx3_rd_finish]

#set_property PACKAGE_PIN K22 [get_ports fx3_dma_rdy]
#set_property IOSTANDARD LVCMOS33 [get_ports fx3_dma_rdy]
#set_property SLEW FAST [get_ports fx3_dma_rdy]

set_property PACKAGE_PIN K25 [get_ports Reset_button2]
set_property IOSTANDARD LVCMOS33 [get_ports Reset_button2]
set_property SLEW FAST [get_ports Reset_button2]

set_property PACKAGE_PIN J24 [get_ports FLAG1]
set_property IOSTANDARD LVCMOS33 [get_ports FLAG1]
set_property SLEW FAST [get_ports FLAG1]

set_property PACKAGE_PIN F23 [get_ports FLAG2]
set_property IOSTANDARD LVCMOS33 [get_ports FLAG2]
set_property SLEW FAST [get_ports FLAG2]

# Power supply regulators EN signals
set_property SLEW FAST [get_ports EN_VD1]
set_property IOSTANDARD LVCMOS33 [get_ports EN_VD1]
set_property PACKAGE_PIN D18 [get_ports EN_VD1]

set_property SLEW FAST [get_ports EN_VD2]
set_property IOSTANDARD LVCMOS33 [get_ports EN_VD2]
set_property PACKAGE_PIN B19 [get_ports EN_VD2]

set_property SLEW FAST [get_ports EN_VA1]
set_property IOSTANDARD LVCMOS33 [get_ports EN_VA1]
set_property PACKAGE_PIN A15 [get_ports EN_VA1]

set_property SLEW FAST [get_ports EN_VA2]
set_property IOSTANDARD LVCMOS33 [get_ports EN_VA2]
set_property PACKAGE_PIN A12 [get_ports EN_VA2]

# Command sequencer signals
set_property SLEW SLOW [get_ports CMD_CLK_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports CMD_CLK_OUT]
set_property PACKAGE_PIN C9 [get_ports CMD_CLK_OUT]

set_property SLEW SLOW [get_ports CMD_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports CMD_DATA]

# FE-I4_rx signals
set_property SLEW SLOW [get_ports DOBOUT]
set_property IOSTANDARD LVCMOS33 [get_ports DOBOUT]

#####################################

#create_clock -name Clk100 -period 10.000 [get_ports Clk100]

# D:/redmine_svn/usb/FX3device/branches/Hans/KX7 firmware/Mercury KX1.ucf:59
#Created by Constraints Editor (xc6slx45-fgg484-2) - 2013/01/25
#OFFSET = OUT AFTER "fx3_pclk_100mhz";
#Created by Constraints Editor (xc6slx45-fgg484-2) - 2013/02/25
#OFFSET = IN 8 ns VALID 7 ns BEFORE "fx3_pclk_100mhz" RISING;
#Created by Constraints Editor (xc7k160t-fbg676-1) - 2013/12/18

set_property PACKAGE_PIN J23 [get_ports fx3_ack]
set_property PACKAGE_PIN K23 [get_ports fx3_rdy]

#create_clock -period 25.000 -name clk40mhz [get_nets clk40mhz]




set_property PACKAGE_PIN J25 [get_ports fx3_rst]

set_property PACKAGE_PIN D9 [get_ports CMD_DATA]
set_property PACKAGE_PIN J11 [get_ports DOBOUT]
set_property PACKAGE_PIN AD18 [get_ports sys_clk_n]
set_property PACKAGE_PIN AC18 [get_ports sys_clk_p]
set_property IOSTANDARD SSTL15 [get_ports sys_clk_n]
set_property IOSTANDARD SSTL15 [get_ports sys_clk_p]

set_property PACKAGE_PIN AD21 [get_ports {PWR_EN[0]}]
set_property PACKAGE_PIN AE21 [get_ports {PWR_EN[1]}]
set_property PACKAGE_PIN AE23 [get_ports {PWR_EN[2]}]
set_property PACKAGE_PIN AF23 [get_ports {PWR_EN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWR_EN[0]}]


create_clock -period 10.000 -name fx3_pclk_100MHz -waveform {0.000 5.000} [get_ports fx3_pclk_100MHz]
create_generated_clock -name CMD_CLK_OUT -source [get_pins icmd/i_cmd_seq_core/CMD_CLK_FORWARDING_INST/C] -divide_by 1 [get_ports CMD_CLK_OUT]

set_false_path -from [get_clocks fx3_pclk_100MHz] -to [get_clocks {clk16mhz_pll clk40mhz_pll clk160mhz_pll clk320mhz_pll CMD_CLK_OUT}]
set_false_path -from [get_clocks fx3_pclk_100MHz] -to [get_clocks {clk16mhz_pll clk40mhz_pll clk160mhz_pll clk320mhz_pll CMD_CLK_OUT}]
